#ifndef RUSHHOUR_GAMESETTINGS_HPP
#define RUSHHOUR_GAMESETTINGS_HPP

#define WINDOW_WIDTH 700
#define WINDOW_HEIGHT 700

#define MARGIN 50

#define GAME_WIDTH (WINDOW_WIDTH - 2 * MARGIN)
#define GAME_HEIGHT (WINDOW_HEIGHT - 2 * MARGIN)

#define LEVEL_COUNT 5

#endif //RUSHHOUR_GAMESETTINGS_HPP
