#ifndef RUSHHOUR_GAMESETTINGS_HPP
#define RUSHHOUR_GAMESETTINGS_HPP

#define WINDOW_WIDTH 700
#define WINDOW_HEIGHT 700

#define MARGIN_TOP 50
#define MARGIN_LEFT 50
#define MARGIN_RIGHT 50
#define MARGIN_BOTTOM 50

#define GAME_WIDTH (WINDOW_WIDTH - MARGIN_LEFT - MARGIN_RIGHT)
#define GAME_HEIGHT (WINDOW_HEIGHT - MARGIN_TOP - MARGIN_BOTTOM)

#define GRID_HEIGHT 6
#define GRID_WIDTH 6

#define CELL_WIDTH GAME_WIDTH / GRID_WIDTH
#define CELL_HEIGHT GAME_HEIGHT / GRID_HEIGHT

#define OUT_SIDE sf::Vector2i(1, 0)




#endif //RUSHHOUR_GAMESETTINGS_HPP
